/* Dated and attributed media context. Labels are not accuracy scores. */
(function(root){
'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const profiles={
 ithome:{name:'iThome',badge:'科技媒体／党派倾向待核定',status:'not-assessed',scope:'2000署名行业采访',text:'本批采用其电讯企业与网络教育产品的同期采访，身份和发言按当时报道理解。',limits:'未取得足以给该媒体作台湾蓝绿归类的研究；预告的商业安排不等于已完成成果。',evidence:[]},
 tnl:{name:'关键评论网',badge:'本人访问／倾向待核定',status:'not-assessed',scope:'2014署名人物访问',text:'本批采用苏巧慧本人回忆职业选择的访问，保留受访身份及采访日期。',limits:'访问自述不等于任命原件；尚未完成该媒体党派倾向的独立核定。',evidence:[]},
 epoch:{name:'大纪元',badge:'2020自述：反中共／法轮功背景',status:'interested-source',scope:'2020-10-02媒体自述；本批台湾署名报道',text:'大纪元自述创办人John Tang为法轮功信仰者，因反对中共迫害及不满相关报道而创刊。此处标明其自述的背景与创刊动机。',limits:'不将集团创刊自述当作2026台湾版逐篇倾向测量，也未据此指定支持台湾某政党；新闻事实另与原始资料交叉核对。',evidence:['media-epoch-self-2020']},
 tku:{name:'淡江时报',badge:'任职大学的校内资料',status:'institutional',scope:'2002、2009人物履历及访问',text:'淡江大学校内媒体发布的任职人物资料与访问，用于追查当时公开的职称。',limits:'校内资料不是独立成效审计，刊载日不等于到职日；未作台湾蓝绿归类。',evidence:[]},
 peopo:{name:'PeoPo公民新闻',badge:'公民记者稿／倾向待核定',status:'not-assessed',scope:'具体投稿及署名',text:'开放平台的公民记者稿件，保留作者和原访问场景；并非公视新闻编辑部自采稿。',limits:'平台背景不能替代投稿作者立场或事实核查，本版未为投稿者指定蓝绿。',evidence:[]},
 intellectual:{name:'新大学政论专栏',badge:'访谈或转载／倾向待核定',status:'not-assessed',scope:'依文章作者、原发和刊载资料识别',text:'本人访问文字与标明原发的转载分别处理，保留原发作者、日期及平台身份。',limits:'转载不是独立采访；本版未取得足以给该平台作当前蓝绿定性的研究。',evidence:[]},
 upmedia:{name:'上报',badge:'倾向待核定',status:'not-assessed',scope:'2017署名采访',text:'本批采用上报陈怡杰的人物访问，经新大学转载，保留原发署名。',limits:'人物自述与任命原件分别标注；尚未完成该媒体倾向的独立核定。',evidence:[]},
 everdant:{name:'常青棋牌休闲馆',badge:'企业创办人自述',status:'interested-source',scope:'企业身份页面；发布日期未明',text:'企业介绍创办人与经营理念的页面，郭玺同时列为麻将最大党主席。',limits:'可用于身份对应，经营成果、社会效果与完整任期需独立材料；未作媒体或党派倾向归类。',evidence:[]},
 doublethink:{name:'台湾民主实验室',badge:'相关机构自述',status:'interested-source',scope:'2023人事声明',text:'研究机构就其成员参选、组织交接及独立性作出的当事方说明。',limits:'人事程序可与法院登记核对；机构自述的中立性及资金情况不能仅凭声明独立认定，未作党派倾向归类。',evidence:[]},
 aneoc:{name:'良心时代运动',badge:'活动主办方记录',status:'interested-source',scope:'受访页面与身份片头；日期未载',text:'活动组织者保存的受访人名录和影音，用于识别当时公开的身份。',limits:'不构成体育成绩认证、雇用任期证明或2026现职确认；本版未作党派倾向归类。',evidence:[]},
 'udn-money':{name:'经济日报',badge:'本文转载平台',status:'platform',scope:'依本篇署名识别原发',text:'本文原发为联合报，经济日报网站承载文章。',limits:'同一集团不同平台的转载仍不是独立采访。',evidence:[]},
 cna:{name:'中央社',badge:'国家通讯社／公设背景',status:'institutional',scope:'制度史及2026-06董监事遴聘资料',text:'中央社自述1996年改制为财团法人；2026年涉己报道依据文化部说明记载董监事由行政院遴聘。',limits:'这些是制度关系，不等于中立认证，也不能直接推定每篇报道支持执政党。本版未据此指定蓝绿。',evidence:['media-cna-history','media-cna-2026']},
 pts:{name:'公视新闻',badge:'公共媒体／未作党派定性',status:'institutional',scope:'路透新闻学研究所2024台湾章',text:'该报告将公视列作公共广播媒体。本版呈现公共媒体属性，未以“公营”替代独立的党派倾向研究。',limits:'公共媒体并不天然保证每条信息无误；报道、评论、采访仍须分别阅读。',evidence:['media-risj-2024']},
 ltn:{name:'自由时报',badge:'路透研究所2024：倾独',status:'attributed',scope:'2024数字新闻报告，非2026逐篇审查',text:'路透新闻学研究所2024台湾章由林丽云撰写，以pro-independent描述自由时报。这里沿用该报告在统独议题上的描述并标注出处。',limits:'“倾独”不是“任何议题都支持民进党”的同义词，也不是新闻准确度评分；历史评述不自动等于现时逐篇结论。',evidence:['media-risj-2024']},
 udn:{name:'联合报',badge:'路透研究所2024：倾统',status:'attributed',scope:'2024数字新闻报告，非2026逐篇审查',text:'路透新闻学研究所2024台湾章将联合报与中国时报描述为pro-unification。本标签注明评述机构和年份，不把它当作永久不变的属性。',limits:'统独维度不能直接替换为对任何政党或所有政策的支持；媒体背景与单篇证据可靠性分开。',evidence:['media-risj-2024']},
 chinatimes:{name:'中国时报',badge:'路透研究所2024：倾统',status:'attributed',scope:'2024数字新闻报告',text:'路透新闻学研究所2024台湾章使用pro-unification描述中国时报。此处记录外部研究的表述，不附加本网站的评价分数。',limits:'这是报告的统独倾向描述，不是对每位记者或每篇稿件的结论。',evidence:['media-risj-2024']},
 cti:{name:'中天新闻',badge:'路透2020称亲中',status:'attributed',scope:'2020-11-18换照报道中的媒体描述',text:'路透社2020年报道使用“广泛被视为pro-China”的措辞描述当时中天，同时记载中天及国民党认为换照决定损害新闻自由。',limits:'此标签指明历史报道的归属和日期，不等于本站裁定其受谁指挥，也不作为2026执照、诉讼或逐篇报道状态的结论。',evidence:['media-cti-reuters']},
 tvbs:{name:'TVBS',badge:'泛蓝之说〔2011争议〕',status:'disputed',scope:'2011-06-18报道的公开争议；未作为2026定论',text:'Taipei Times记载吴宗宪称TVBS泛蓝；TVBS发言人针对国民党持股的说法反驳并提出法律行动。这里展示一项有异议的历史描述，而非本网站的直接归类。',limits:'股权和编辑倾向是不同命题；这项言论争议也不是独立的近期内容分析，不能拿来证明2026每篇新闻的立场或真假。',evidence:['media-tvbs-2011']},
 ftv:{name:'民视新闻',badge:'2010监测称偏泛绿',status:'attributed-disputed-method',scope:'2010-11-01至17，晚间新闻样本',text:'Taipei Times转述中华传播学会当年对10家电视台、545条选举新闻的监测，报告称民视与三立报道有利于泛绿。',limits:'同一报道指出研究者政治背景受到质疑。该标签保留方法与争议，不把2010样本当成2026的直接测量。',evidence:['media-tv-2010']},
 setn:{name:'三立新闻',badge:'2010监测称偏泛绿',status:'attributed-disputed-method',scope:'2010-11-01至17，晚间新闻样本',text:'中华传播学会当年监测被Taipei Times报道为三立及民视对泛绿较有利；这是有限时段、特定节目样本的研究结论。',limits:'研究者背景亦受到质疑。网络文字稿、不同年代及评论节目不能自动继承这项样本结论。',evidence:['media-tv-2010']},
 chinadaily:{name:'中华日报',badge:'国民党党营历史',status:'historical-institutional',scope:'党营事业沿革，含2006停止经费供应记录',text:'党产会史料整理记载中华日报的国民党党营历史，并述及2006年国民党停止经费供应。此处标注的是历史机构关系。',limits:'没有用这段历史代替2026股权调查，也未直接推定当前每篇报道的蓝绿倾向。',evidence:['media-chinadaily-history']},
 newtalk:{name:'Newtalk新闻',badge:'倾向待核定',status:'not-assessed',scope:'仅核对平台自述',text:'已取得平台关于公司及营运的自述，尚未取得足以作本版倾向归类的近年独立研究。',limits:'不把未核定写成中立，也不根据一篇标题或转载平台推定全部倾向。',evidence:['media-newtalk-about']},
 mnews:{name:'镜新闻',badge:'倾向待核定',status:'not-assessed',scope:'本批来源未完成独立倾向核查',text:'保留原报道媒体身份；尚不为其填写确定的蓝绿结论。',limits:'机构名称相近或存在转载关系，不代表可以把另一媒体的倾向或所有权直接转移过来。',evidence:[]},
 ftnn:{name:'FTNN新闻网',badge:'倾向待核定',status:'not-assessed',scope:'本批资料范围',text:'本版尚未取得可审阅的媒体倾向评述依据。',limits:'不以未评述代表中立，也不以一篇报道的语气作全媒体归类。',evidence:[]},
 mirror:{name:'镜周刊',badge:'转载平台；原发另标',status:'platform',scope:'本批文章署名',text:'本文依原文署名识别原发媒体；镜周刊在此承担转载平台角色。',limits:'转载不是又一个独立采访来源。只在原文确实标出原发时才合并来源关系。',evidence:[]},
 yahoo:{name:'Yahoo',badge:'转载平台；原发另标',status:'platform',scope:'本批文章署名',text:'按稿件署名保留原发媒体，Yahoo列为承载平台。',limits:'平台与原发媒体的编辑倾向不能混用，同一原稿的多站转载不是独立交叉验证。',evidence:[]},
 cts:{name:'华视新闻',badge:'倾向待核定',status:'not-assessed',scope:'区分自采及中央社转载',text:'华视自采稿与路径、署名明确的中央社转载稿分别处理。',limits:'本版未对其指定蓝绿；若本文转自中央社，倾向及背景说明指向原发媒体。',evidence:[]},
 people:{name:'人民网',badge:'本文转载平台',status:'platform',scope:'本批标明中央社来源的文章',text:'本批文章依据原文来源保留中央社为原发，不将承载平台另算独立采访。',limits:'不以转载平台的背景覆盖原稿署名；对有实质改写的文章需另行核查。',evidence:[]},
 scmp:{name:'南华早报',badge:'本文转载平台',status:'platform',scope:'本批路透署名文章',text:'本批媒体评述材料署名Reuters，南华早报为转载平台。',limits:'仅适用于该篇，不把全站文章都视为路透稿。',evidence:[]},
 reuters:{name:'路透社',badge:'通讯社原稿／未作党派定性',status:'not-assessed',scope:'本批所用署名稿',text:'保留通讯社原稿身份；本文未为其建立台湾蓝绿归类。',limits:'出处和日期支持追查，机构名本身不能代替事实核验。',evidence:[]},
 risj:{name:'路透新闻学研究所',badge:'外部研究，非路透新闻稿',status:'research',scope:'牛津大学机构的2024报告',text:'本版使用其数字新闻报告中有作者、年份的媒体描述。该研究报告不是同名通讯社发表的新闻报道。',limits:'引用时保留报告时段、作者、维度和材料局限，不将其扩展成候选人评价。',evidence:['media-risj-2024']},
 'taipei-times':{name:'Taipei Times',badge:'倾向未在本批核定',status:'not-assessed',scope:'历史研究及争议报道',text:'本文是媒体报道的转述，非所报道机构的原始数据库。',limits:'对其倾向尚未完成独立评述；被引用的研究者说法不直接成为本网站判断。',evidence:[]},
 'official-tw':{name:'台湾公部门资料',badge:'官方原始材料',status:'institutional',scope:'具体发布机关及发布日期',text:'政府、议会或司法机关的履历、公告、统计与说明。',limits:'官方资料可证明发布机关作出的决定或主张，不自动证明争议中所有指控成立。',evidence:[]},
 'official-us':{name:'美国公部门资料',badge:'官方档案／监管记录',status:'institutional',scope:'具体机构与公开时点',text:'包括专业监管机构原始记录、公开听证与本人提交证词。',limits:'按材料类型分别理解：监管状态有查询时点，收录证词不等于政府认可全部判断。',evidence:[]},
 'official-cn':{name:'中国大陆公部门资料',badge:'官方立场／机关公告',status:'institutional',scope:'具体发布机关及公告时点',text:'按发布机关名义呈现行政措施或立场。',limits:'与被指对象的回应分开；公告中的政治定性不直接作为网站结论。',evidence:[]},
 party:{name:'政党／当事方',badge:'当事方自述',status:'interested-source',scope:'资料发布时点',text:'用于证明本人或组织如何自我介绍、提出何种主张。',limits:'自述不等于独立事实认证；教育成效、任职、财务等仍需对应原件。',evidence:[]},
 association:{name:'中华民国健美健身协会',badge:'任职机构历史记录',status:'institutional',scope:'协会历任名册；起止年月未载',text:'协会自己的职务历史记录，适用于名册列明的届次和代理身份。',limits:'不将旧职推定为现职，也不以这份名册代替教练聘书或比赛成绩。',evidence:[]},
 trustdemocracy:{name:'台北市信民两岸研究协会',badge:'民调委托方自行发布',status:'interested-source',scope:'2026-09-22台北市长民调报告',text:'协会为调查出资并在自有网站发布报告及方法说明；这是委托方自发报告，不是独立审计。',limits:'可核对委托方公布的题目、抽样说明和结果；原始访问记录及独立复核材料未收录。',evidence:[]},
 concords:{name:'康和证券集团',badge:'项目合作方年度自述',status:'interested-source',scope:'2014年度社会责任报告中的课程项目',text:'合作方的原始报告，用于核对当时项目安排和被邀请者身份。',limits:'项目规模与学习效果属于报告方自述，不等于独立成效评估，也不证明参与者是该公司雇员。',evidence:[]},
 retailer:{name:'书店／出版资料',badge:'作者或出版方自述',status:'interested-source',scope:'书目所列出版时点',text:'作者简介及内容说明属于出版资料，不是书店独立调查得出的履历认证。',limits:'保留“自述”及未知任期；商品效果宣传不作为研究已证明的事实。',evidence:[]},
 commons:{name:'Wikimedia Commons',badge:'图像档案／授权记录',status:'repository',scope:'具体文件说明页',text:'用于核对图片原作者、文件来源、拍摄时点与许可，不是台湾新闻媒体。',limits:'文件说明的日期不自动等于拍摄日期；本站保留原说明的精度。',evidence:[]},
 community:{name:'社区或民间资料整理',badge:'非官方整理',status:'repository',scope:'本批采用的数据版本',text:'社区条目、选举统计整理或开源地图，不假装是政府原始公报。',limits:'原始数据核查状态逐项标示，域名中有gov也不等于政府网站。',evidence:[]},
 ncl:{name:'国家图书馆',badge:'国家级图书馆／非新闻媒体',status:'institution',scope:'作者履历索引',text:'国家图书馆书目整合系统提供作者记录和其引用的书目资料。',limits:'作者履历由被索引的计划或个人资料提供，不等同雇主聘书或任命公报；本批按索引注明的资料来源与日期精度呈现。',evidence:[]},
 'nccu-lib':{name:'国立政治大学图书馆',badge:'学术图书馆／非新闻媒体',status:'institution',scope:'政府官职任命公报数据库',text:'以结构化索引提供公报命令日期和职务查询。',limits:'索引不等同完整任免公报；具体生效与离职日期仍需查阅原始公报。',evidence:[]},
 other:{name:'来源机构',badge:'倾向待核定',status:'not-assessed',scope:'本批资料范围',text:'本批尚未建立足够的独立评述依据。',limits:'待核定不是中立认证，不根据标题或域名猜测立场。',evidence:[]}
};
const hostMap={'www.gov.taipei':'official-tw','gov.taipei':'official-tw','www.cna.com.tw':'cna','news.pts.org.tw':'pts','news.ltn.com.tw':'ltn','election.ltn.com.tw':'ltn','money.udn.com':'udn-money','udn.com':'udn','www.chinatimes.com':'chinatimes','ctinews.com':'cti','news.tvbs.com.tw':'tvbs','www.ftvnews.com.tw':'ftv','sport.ftvnews.com.tw':'ftv','finance.ftvnews.com.tw':'ftv','www.setn.com':'setn','www.mirrormedia.mg':'mirror','newtalk.tw':'newtalk','www.mnews.tw':'mnews','www.ftnn.com.tw':'ftnn','tw.stock.yahoo.com':'yahoo','tw.news.yahoo.com':'yahoo','news.cts.com.tw':'cts','tw.people.com.cn':'people','www.scmp.com':'scmp','www.reuters.com':'reuters','reutersinstitute.politics.ox.ac.uk':'risj','www.taipeitimes.com':'taipei-times','www.mipartysor.tw':'party','www.sanmin.com.tw':'retailer','www.taaze.tw':'retailer','www.miparty.org':'party','crm.ntpu.edu.tw':'official-tw','tcmb.culture.tw':'official-tw','bulletin.cec.gov.tw':'official-tw','commons.wikimedia.org':'commons','zh.wikipedia.org':'community','votetw.com':'community','govtw.org':'community','github.com':'community'};
const agencyNames={'nco.gov.taipei':'台北市工务局新建工程处','www.nyc.gov':'纽约市政府','www.usgs.gov':'美国地质调查局','serv.gcis.nat.gov.tw':'经济部商工行政资料','isbn.ncl.edu.tw':'国家图书馆ISBN中心','pr.ntnu.edu.tw':'国立台湾师范大学','apps.calbar.ca.gov':'加州律师监管机构（State Bar）','data.judicial.gov.tw':'司法院裁判资料','ws.moi.gov.tw':'内政部公开资料','sec.gov.taipei':'台北市政府秘书处','crm.ntpu.edu.tw':'国立台北大学','tcmb.culture.tw':'国家文化记忆库／国立台湾历史博物馆','bulletin.cec.gov.tw':'中央选举委员会公报库','www.tipo.gov.tw':'智慧财产局','www.uscc.gov':'美中经济与安全评估委员会','www.gov.taipei':'台北市政府','gov.taipei':'台北市政府','www.ly.gov.tw':'立法院','www.judicial.gov.tw':'司法院','www.gwytb.gov.cn':'国务院台办','www.mac.gov.tw':'陆委会','www.president.gov.tw':'总统府','law.moj.gov.tw':'全国法规资料库','db.cec.gov.tw':'中央选举委员会','web.cec.gov.tw':'中央选举委员会','www.stories.cipas.gov.tw':'党产会史料'};
const originOverrides={'us':'chinadaily','t-chiang-us':'chinadaily','t-chiang-primary':'cna','t-order':'udn'};
function resolve(id,d){const s=d.sources[id];if(!s)return null;let url;try{url=new URL(s.url);}catch{return null;}
 if(!['https:','http:'].includes(url.protocol))return null;
 let platformId=s.publisherId||hostMap[url.hostname]||(url.hostname.endsWith('.gov.tw')?'official-tw':url.hostname.endsWith('.gov.cn')?'official-cn':'other');
 let publisherId=s.originalPublisherId||originOverrides[id]||(url.hostname==='news.cts.com.tw'&&url.pathname.startsWith('/cna/')?'cna':platformId);
 const profile=profiles[publisherId]||profiles.other,platform=profiles[platformId]||profiles.other;
 const platformName=platform.name==='来源机构'?url.hostname:platform.name;
 const publisherName=(publisherId.startsWith('official-')?agencyNames[url.hostname]:null)||(profile.name==='来源机构'?(s.publisherName||url.hostname):profile.name);
 return {id,source:s,publisherId,platformId,publisherName,platformName,profile,syndicated:publisherId!==platformId,publishedAt:s.publishedAt||s.date||null,updatedAt:s.updatedAt||null,dateLabel:s.dateLabel||'来源日期',checkedAt:s.checkedAt||d.checkedAt||'2026-10-02'};
}
function render(id,label,d=root.ATLAS){const m=resolve(id,d);if(!m)return'';const s=m.source;return `<span class="source-citation"><a class="inline-source" href="${E(s.url)}" target="_blank" rel="noopener noreferrer">${E(label||s.title)} ↗</a><span class="source-meta"><span>${E(m.publisherName)}${m.syndicated?' → '+E(m.platformName)+'转载':''}</span><time>${m.publishedAt?E(m.dateLabel)+' '+E(m.publishedAt):'发布日期未明'}</time>${m.updatedAt?'<span>更新 '+E(m.updatedAt)+'</span>':''}<button type="button" class="media-context-button" data-media-profile="${E(m.publisherId)}" aria-haspopup="dialog">${E(m.profile.badge)} ⓘ</button></span></span>`;}
function refs(ids,d=root.ATLAS){return [...new Set(ids||[])].map(id=>render(id,null,d)).join('');}
function room(d=root.ATLAS){return Object.entries(d.sources).map(([id,s])=>`<article class="source-entry" data-source-id="${E(id)}">${render(id,null,d)}<p class="source-type">${E(s.kind||'资料类型待补')} · 本站检查 ${E(s.checkedAt||d.checkedAt)}${s.note?' · '+E(s.note):''}</p></article>`).join('');}
function showProfile(id){const p=profiles[id]||profiles.other;let el=document.getElementById('media-context-dialog');if(!el){el=document.createElement('dialog');el.id='media-context-dialog';el.setAttribute('aria-labelledby','media-context-title');document.body.append(el);}
 el.innerHTML=`<div class="dialog-bar"><span class="eyebrow">MEDIA CONTEXT / 谁在报道</span><button type="button" data-close-media aria-label="关闭媒体背景">✕</button></div><div class="sources-inner"><h2 id="media-context-title">${E(p.name)}</h2><p class="media-context-badge">${E(p.badge)}</p><p><b>依据适用时期：</b>${E(p.scope)}</p><p>${E(p.text)}</p><p class="note">${E(p.limits)}</p><h3>描述依据</h3>${p.evidence.length?p.evidence.map(s=>{const row=root.ATLAS.sources[s];return row?`<p><a href="${E(row.url)}" target="_blank" rel="noopener noreferrer">${E(row.title)} ↗</a><br><small>${E(row.date||'发布日期未注明')}</small></p>`:'';}).join(''):'<p>尚未收录可以支撑明确党派归类的研究，不以空白冒充中立。</p>'}<p>倾向、机构背景、文章类型与事实准确性是不同问题。本页不提供媒体可信度分数，不把转载算作独立交叉验证。</p></div>`;
 el.querySelector('[data-close-media]').onclick=()=>el.close();if(!el.open)el.showModal();}
if(typeof document!=='undefined')document.addEventListener('click',e=>{const b=e.target.closest('[data-media-profile]');if(b){e.preventDefault();showProfile(b.dataset.mediaProfile);}});
const api={profiles,resolve,render,refs,room};if(typeof module!=='undefined')module.exports=api;else root.AtlasMedia=api;
})(typeof window==='undefined'?globalThis:window);
