'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=structuredClone(require('../public/data.js'));require('../public/taipei-research.js').apply(D);
const before=JSON.stringify(D.people.filter(p=>p.city!=='taipei')),P=require('../public/taipei-profile-data.js'),M=require('../public/media.js');P.apply(D);
test('all six Taipei profiles receive independent work and politics arrays',()=>{assert.deepEqual(P.validate(D),[]);for(const p of D.people.filter(p=>p.city==='taipei')){assert.ok(Array.isArray(p.workHistory));assert.ok(Array.isArray(p.politicalHistory));assert.ok(p.careerNote);}});
test('every profile has at most three attributable campaign expressions',()=>{for(const p of Object.values(P.data.people)){assert.ok(p.slogans.length<=3);for(const x of p.slogans){assert.ok(x.date&&x.sources.length&&x.context);assert.equal(typeof x.verbatim,'boolean');assert.ok([2022,2024,2026].includes(x.electionYear));}}});
test('oral, paraphrased and historic campaign language are distinct',()=>{assert.ok(P.data.people.kuo.slogans.length<=3);assert.ok(!P.data.people.kuo.slogans.some(x=>["参选到底","选贤与能"].includes(x.text)));assert.equal(P.data.people['hsiao-w'].slogans[0].verbatim,false);assert.equal(P.data.people.tang.slogans[0].electionYear,2022);assert.equal(P.data.people['lin-c'].slogans[0].electionYear,2024);});
test('six attributed portraits ship with the site',()=>{for(const [id,p] of Object.entries(P.data.people)){assert.equal(p.photo.status,'linked');assert.equal(p.photo.delivery,'bundled-file');assert.match(p.photo.url,new RegExp('^photos/'+id+'\\.(jpg|png)$'));assert.ok(fs.statSync(path.join(__dirname,'../public',p.photo.url)).size>1000);assert.ok(p.photo.credit&&p.photo.license&&p.photo.note);assert.ok(['open-license','editorial-quotation'].includes(p.photo.publicationBasis));}assert.equal(D.taipeiEnrichment.bundledPhotoFiles,6);});
test('single interpreting job is not turned into a political appointment',()=>{const p=P.data.people['hsiao-w'];assert.match(p.workHistory[0].role,/单次/);assert.match(p.workHistory[0].note,/一次/);assert.ok(!p.politicalHistory.some(x=>/口译/.test(x.role)));});
test('missing career dates and missing employers are not invented',()=>{assert.equal(P.data.people.tang.workHistory.length,0);assert.match(P.data.people.tang.careerNote,/不等于/);assert.ok(P.data.people.shen.workHistory.some(x=>x.date==='最迟2017-08已任'));});
test('CNA syndication is recognized on CTS and People platforms',()=>{for(const id of ['t-forum-apr','t-forum-jun','t-flood','t-kit','t-chiang-primary']){assert.equal(M.resolve(id,D).publisherId,'cna');assert.equal(M.resolve(id,D).syndicated,true);}});
test('publisher identity follows original signature, not host name',()=>{assert.equal(M.resolve('t-order',D).publisherName,'联合报');assert.equal(M.resolve('t-order',D).platformName,'经济日报');assert.equal(M.resolve('t-chiang-us',D).publisherName,'中华日报');assert.equal(M.resolve('v3-hsiao-policy',D).publisherName,'三立新闻');});
test('tendency descriptions carry named dated evidence and limitations',()=>{for(const id of ['ltn','udn','cti','ftv','setn','tvbs']){const p=M.profiles[id];assert.ok(p.scope&&p.limits&&p.evidence.length);for(const sid of p.evidence)assert.ok(D.sources[sid]);}assert.match(M.profiles.tvbs.limits,/不是独立/);assert.match(M.profiles.ftv.limits,/受到质疑/);});
test('every source citation includes publisher, date state and context action',()=>{for(const id of Object.keys(D.sources)){const s=M.render(id,null,D);assert.ok(s.includes('source-meta'),id);assert.ok(s.includes('data-media-profile'),id);assert.ok(/来源日期|图像记录日期|裁判日期|文件编制|书目期别|发布|发布日期未明/.test(s),id);}});
test('no false neutral rating and no executable source URL',()=>{assert.equal(M.profiles.newtalk.status,'not-assessed');const bad={...D,sources:{bad:{title:'bad',url:'javascript:alert(1)'}}};assert.equal(M.render('bad',null,bad),'');const hostile={...D,sources:{x:{title:'<svg onload=alert(1)>',url:'https://example.com'}}};assert.ok(!M.render('x',null,hostile).includes('<svg'));});
test('profile application is idempotent and preserves other cities',()=>{const after=JSON.stringify(D.people);P.apply(D);assert.equal(JSON.stringify(D.people),after);assert.equal(JSON.stringify(D.people.filter(p=>p.city!=='taipei')),before);assert.equal(D.polls.length,0);});
test('new assets and hook order exist in the HTML',()=>{const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');for(const f of ['taipei-profile-data.js','media.js','profile-details.js','profile-details.css'])assert.ok(html.includes(f));assert.ok(html.indexOf('taipei-profile-data.js')<html.indexOf('app.js'));assert.ok(html.indexOf('media.js')<html.indexOf('research-ui.js'));});

test('publication, roster update and image dates are not conflated',()=>{assert.equal(M.resolve('roster',D).publishedAt,'2026-09-04');assert.equal(M.resolve('roster',D).updatedAt,'2026-09-19');assert.match(M.render('v3-chiang-photo',null,D),/图像记录日期/);});

test('Taipei government is not misclassified as a news outlet',()=>{assert.equal(M.resolve('t-chiang-bio',D).publisherId,'official-tw');assert.equal(M.resolve('t-chiang-bio',D).publisherName,'台北市政府');});

test('round32 data loader is a valid script element and loads before the app',()=>{const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');assert.match(html,/src="career-foreign-round31\.js"><\/script><script defer="" src="career-foreign-round32\.js"><\/script>/);assert.ok(html.indexOf('career-foreign-round32.js')<html.indexOf('app.js'));});
