'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),D=require('../public/data.js'),U=require('../public/domain.js');
require('../public/taipei-research.js').apply(D);
const P=require('../public/taipei-profile-data.js');P.apply(D);
require('../public/four-city-data.js').apply(D);
require('../public/policy-data.js').apply(D);
require('../public/policy-lai-round78.js').apply(D);
require('../public/policy-hsieh-round79.js').apply(D);
require('../public/policy-hsieh-round82.js').apply(D);
require('../public/policy-kuo-round80.js').apply(D);
require('../public/policy-kuo-referendum-round55.js').apply(D);
require('../public/policy-wang-empty-round47.js').apply(D);
require('../public/policy-wang-search-round75.js').apply(D);
require('../public/policy-taipei-coverage-round81.js').apply(D);
require('../public/career-foreign-round3.js').apply(D);
require('../public/career-foreign-round24.js').apply(D);
require('../public/career-foreign-round29.js').apply(D);
require('../public/career-foreign-round30.js').apply(D);
require('../public/career-foreign-round31.js').apply(D);
require('../public/career-foreign-round32.js').apply(D);
require('../public/career-foreign-round33.js').apply(D);
require('../public/career-foreign-round34.js').apply(D);
require('../public/career-tainan-chen-anchor-round35.js').apply(D);
require('../public/career-chen-foreign-round46.js').apply(D);
require('../public/career-chiang-silicon-valley-round48.js').apply(D);
require('../public/career-ko-role-dates-round50.js').apply(D);
require('../public/career-ko-dean-end-round54.js').apply(D);
require('../public/career-chen-tv-timeline-round51.js').apply(D);
require('../public/career-chen-work-review-round72.js').apply(D);
require('../public/career-lai-role-dates-round52.js').apply(D);
require('../public/career-hsiao-principal-dates-round49.js').apply(D);
require('../public/career-su-h-community-round36.js').apply(D);
require('../public/career-su-role-dates-round53.js').apply(D);
require('../public/career-wang-work-round37.js').apply(D);
require('../public/career-chang-discipline-round38.js').apply(D);
require('../public/career-wang-education-round39.js').apply(D);
require('../public/career-tang-education-review-round40.js').apply(D);
require('../public/career-tang-channel-round68.js').apply(D);
require('../public/career-wang-trademark-round41.js').apply(D);
require('../public/career-wang-review-round69.js').apply(D);
require('../public/career-lin-sports-archive-round42.js').apply(D);
require('../public/career-lin-review-round74.js').apply(D);
require('../public/career-kuo-service-span-round56.js').apply(D);
require('../public/career-shen-us-city-governance-round57.js').apply(D);
require('../public/career-ko-tv-timeline-round58.js').apply(D);
require('../public/career-yeh-street-performance-round59.js').apply(D);
require('../public/career-ho-term-dates-round60.js').apply(D);
require('../public/career-legislator-terms-round61.js').apply(D);
require('../public/career-hung-l-work-claims-round62.js').apply(D);
require('../public/career-hung-l-election-round73.js').apply(D);
require('../public/career-su-h-ccp-statement-round63.js').apply(D);
require('../public/career-su-h-2024-result-round64.js').apply(D);
require('../public/career-su-h-publisher-round70.js').apply(D);
require('../public/career-hsiao-l-tour-guide-round71.js').apply(D);
require('../public/career-ho-work-round65.js').apply(D);
require('../public/career-yeh-campus-round67.js').apply(D);
require('../public/career-chang-review-round76.js').apply(D);
require('../public/career-work-coverage-round77.js').apply(D);
require('../public/career-hung-f-registry-round86.js').apply(D);
require('../public/career-yeh-company-registry-round87.js').apply(D);
require('../public/career-tang-work-round83.js').apply(D);
require('../public/foreign-coverage-round84.js').apply(D);
require('../public/career-political-coverage-round85.js').apply(D);
const M=require('../public/election-map-data.js');M.apply(D);
const profileErrors=P.validate(D);if(profileErrors.length)throw new Error(profileErrors.join('\n'));
if(process.env.ATLAS_PUBLIC_RELEASE==='1')for(const p of D.people.filter(p=>p.city==='taipei')){
 if(p.photo?.delivery!=='bundled-file'||!['open-license','editorial-quotation'].includes(p.photo.publicationBasis)||!p.photo.credit||!p.photo.note)throw new Error('Missing publication basis: '+p.id);
 if(!/^photos\/[a-z-]+\.(?:jpg|png)$/.test(p.photo.url)||!fs.existsSync(path.join(root,'public',p.photo.url)))throw new Error('Missing bundled portrait: '+p.id);
}
const errors=U.validateData(D);if(errors.length)throw new Error(errors.join('\n'));
for(const p of D.people)for(const x of p.policies)if(!D.policyTopics[x.topic]||!x.text||!x.date||!x.electionYear||!x.sources.length||x.sources.some(s=>!D.sources[s]))throw new Error('Invalid policy: '+p.id);
for(const p of D.people)if(p.policyCoverage?.sources?.some(s=>!D.sources[s]))throw new Error('Invalid policy coverage sources: '+p.id);
for(const p of D.polls)if(!D.people.some(x=>x.city===p.city)||p.sources.some(s=>!D.sources[s])||p.results.some(r=>!D.people.some(x=>x.id===r.person&&x.city===p.city)))throw new Error('Invalid poll references');
const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.cpSync(path.join(root,'public'),dist,{recursive:true});fs.writeFileSync(path.join(dist,'.nojekyll'),'');
// Remove restricted survey data from release bytes, not only the interface.
if(U.blackout()){const file=path.join(dist,'election-map-data.js'),pack=M.forRelease();fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace(/const pack=.*?;(?=\nfunction)/s,()=> 'const pack='+JSON.stringify(pack)+';'));}
// GitHub Pages caches scripts; bind each asset URL to its delivered content.
const htmlPath=path.join(dist,'index.html');
fs.writeFileSync(htmlPath,fs.readFileSync(htmlPath,'utf8').replace(/((?:src|href)=")([^"#]+\.(?:js|css))(")/g,(_,prefix,file,suffix)=>{
 const digest=require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(dist,file))).digest('hex').slice(0,12);
 return prefix+file+'?v='+digest+suffix;
}));
console.log('Built static site: '+dist);
